### PR TITLE
Fix temperature table Fix #85

### LINKED ISSUE #85: Thermometer's value is incorrectly drawn
https://github.com/niner-games/lost-dutchman-mine/wiki/Interface.-Control-Panel

The bar that is suppose to denote current temperature is drawn to far to the left and "jumps" of the actual thermometer's bulb.

It is less noticeable in the default (windowed) app view:

t1

And much more when game is in full-screen mode:

t2

In addition:

- temperature knob is using pale `#ff0000` red color which makes it flat while original game is using two colors:
    - `#ae0000` for the outset / border
    - `#ef0000` for the inset,
- the bulb image is missing
- the background image is cut without surrounding 1-pixel border which also makes the whole thermometer flat. 

Please, see the original image for reference: 

image

Please, not that in-game temperature never drops below 30 F, so the bottom part of the thermometer (with bulb) can be drawn as static, all-the-time the same image:

image

More thermometer's images [can be found at our Wiki](https://github.com/niner-games/lost-dutchman-mine/wiki/Interface.-Control-Panel#thermometer).

### PR DESCRIPTION
**Pull request by MechanikGamer**
I've made several updates to the temperature display in the game to address the issues reported:

Positioning Correction: I've adjusted the positioning of the temperature bar. It now properly aligns with the thermometer's bulb across both windowed and full-screen modes, eliminating the previous misalignment and "jumping" effect.

Color Updates: The temperature knob now utilizes a dual-color scheme to enhance its three-dimensional appearance:

Outset/border is now #ae0000
Inset is #ef0000
Bulb Image: I've added the missing bulb image at the bottom of the thermometer, enhancing the authenticity and visual appeal of the display.

Background Image: The background image now includes a surrounding 1-pixel border, which corrects the previously flat appearance of the thermometer.

Optimization: The static image of the thermometer, including the red bulb, has been optimized. It now retains the same pixel dimensions but is 19% smaller in file size, improving performance without compromising visual quality.

These updates should provide a more accurate and visually appealing temperature display, closely matching the original game's aesthetics.

Zrzut ekranu 2024-04-17 o 00 48 54

### CODE REVIEW

**Comment by mrfatguy** [comment]
@MechanikGamer Thanks for your contribution and welcome to the project! @MadejaMaciej, our core developer will review your PR and merge it or provide you with the feedback, if any changes will be necessary.

Can you provide link to the base image from which you have cut-off the thermometer's bulb?

Are 100% sure that you have used 4K (3840x2160 px) image as a source or that you changes will look good in 4K resolution and scale down to all other window dimensions or screen resolutions? Because this is our base assumption that we develop entire game in 4K and nicely down-scale it to all other resolutions.

Thanks again for your contribution.

**Comment by MadejaMaciej** [comment]
I'll check it and merge once I will be near my PC (could be a little bit later today).

Thanks for contribution! I really aprreciate it!

**Comment by MechanikGamer** [comment]
Thank you for your warm welcome! Here is the URL to the base image I used for the thermometer's bulb, which I sourced from your wiki: [.](https://private-user-images.githubusercontent.com/2903392/310586494-980eb289-6c95-4d4b-9dc2-52f0ee60e7e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNDIyMjMsIm5iZiI6MTcxMzM0MTkyMywicGF0aCI6Ii8yOTAzMzkyLzMxMDU4NjQ5NC05ODBlYjI4OS02Yzk1LTRkNGItOWRjMi01MmYwZWU2MGU3ZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTdUMDgxODQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODM1YzQ4MzI3YjVhN2RiYzIxNGJkZmM1YTU4MzhmMDg2MmIzMDIyNGNiODI5OGJlMWQ2OWI0MWUwM2FmZTlkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.50i7Zwd8x4nsu7ReRMPN7hfClbx6-2u6NHkKX5i3jkg) It appears to have the same width and height in pixels as required.

Regarding the resolution, I must admit I'm not entirely sure how it will perform on a 4K screen since I do not have access to one. However, I did notice that there were two overlapping divs in the code, which I adjusted by removing one and adding borders to enhance the visual depth, aiming to avoid a flat appearance.

Please let me know if further adjustments are needed to meet the 4K resolution standards.

Thanks again for the opportunity to contribute!

**Comment by mrfatguy** [comment]
You "appearance out of nowhere" made as really surprised (and really, really happy)! 😄. But in the same time I had [developer guide](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Coding) in total mess. I have quickly completed it right now, so please, familiarize yourself with it, if you are willing to do any other change for us.

I can't access your image, because you have used underlying Amazon link (and GitHub expire them very often). If you wish to share any image, make sure that you look into source of each page (edit it) and share the GitHub link. But in this particular case it doesn't matter, because we already have a corresponding image [here](https://github.com/niner-games/lost-dutchman-mine/wiki/Interface.-Control-Panel#thermometer). Only, as you can see, I still haven't provided measurements (because, again, I was surprised that you have already completed this ticket). If you wish, you can compare your and this image.

No, please, as long as @MadejaMaciej did not provide any feedback, do not change anything in this PR. We should be able to handle it ourselves.

Rather, if you whish, read the [developer guide](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Coding) and consider, if you don't want to make any other issue. Thanks again.

**Comment by MadejaMaciej** [comment]
Okay, I have to change two things in that PR, but will do it myself. Will merge it to #85 branch in here, add the change to changelog and crop the termometer image, so it will not have this background at the outer part of the image. I know it was like that in wiki, probably will need to add cropped out assets later to it. 

On naming branch matter (which we need to add to wiki) is we should use as a branch name, #number-of-ticket . That will tell us if someone is working on that feature already automatically.

**Review by MadejaMaciej — APPROVED** [review]

**Pull request merged**
